.de EX
.ne 5
.if n .sp 1
.if t .sp .5
.nf
.in +.5i
..
.de EE
.fi
.in -.5i
.if n .sp 8
.if t .sp .5
..
.TH skeleton-package 8 "May 23, 2019"
.SH NAME
skeleton-package\- Layout of a Debian package.
.SH SYNOPSIS
.B skeleton-package
.PP
Summarize your application.
.SH DESCRIPTION
More lengthy description of your application.
.SS "Command reference:"
.TP
\fBskeleton-package\fR
Does absolutely nothing.
.TP
.SH SEE ALSO
None
.SH BUGS
See/report bugs at https://github.com/angela-d/brain-dump
.SH AUTHOR
The text for this page was written by Angela <angelad@disroot.org> for the Debian GNU/Linux system (but may be used by
others).
.SH COPYRIGHT
Copyright  (C) 2019 Angela.  License GPLv3: GNU
GPL version 3 only <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
